name: dev_hero
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#32c0db"
  image: assets/images/icon.png
  android_12:
    color: "#32c0db"
    image: assets/images/icon.png